package aof

import (
	"bytes"
	"encoding/binary"
	"os"
	"testing"
	"time"
)

// The other half of turning v1.0's compatibility promise into something that
// breaks loudly. ADR 0007 puts append-only file **format version 1** inside the
// promise: a file written by any 1.x is readable by any other 1.x, because data
// outlives the process that wrote it.
//
// testdata/v1-format.aof is committed, and it is data rather than output. It was
// produced once, through OpenFile so that it carries the real header, and it
// must never be regenerated by the test that reads it — a golden file the test
// rewrites when it disagrees is a test that always passes. genfixture_test.go
// writes it only when KV_WRITE_FIXTURE=1, which is not set anywhere.

const fixturePath = "testdata/v1-format.aof"

// recordedState is what the fixture encodes, written out by hand rather than
// derived from the file. Deriving it from the file would compare the file to
// itself.
type recordedState struct {
	key      string
	value    string
	hasTTL   bool
	expireMS int64
}

var fixtureSets = []recordedState{
	{key: "plain", value: "value"},
	{key: "binary\r\n\x00", value: "a\r\nb"},
	{key: "with-ttl", value: "42", hasTTL: true, expireMS: 1893456000000},
	{key: "empty", value: ""},
}

var fixtureDeletes = []string{"gone-1", "gone-2", "gone-3"}

// collector records what replay applied, so the assertions are about the
// decoded effects rather than about bytes.
type collector struct {
	sets    []recordedState
	deletes []string
}

func (c *collector) Set(key, value string, expiresAt time.Time, hasTTL bool) {
	s := recordedState{key: key, value: value, hasTTL: hasTTL}
	if hasTTL {
		s.expireMS = expiresAt.UnixMilli()
	}
	c.sets = append(c.sets, s)
}

func (c *collector) Delete(key string) bool {
	c.deletes = append(c.deletes, key)
	return true
}

// TestFormatVersionOneStillReplays is the promise: this exact file, written by
// the format we shipped, still reconstructs the state it encodes.
//
// A change to the encoding that would strand existing files fails here rather
// than at somebody's next restart.
func TestFormatVersionOneStillReplays(t *testing.T) {
	f, err := os.Open(fixturePath)
	if err != nil {
		t.Fatalf("opening the committed fixture: %v", err)
	}
	defer f.Close()

	// Replay reads the header itself; consuming it here first left it reading
	// record bytes as a header and reporting the fixture as a foreign file.
	var got collector
	// A replay instant far before the fixture's deadline, so the TTL-bearing
	// record survives and its expiry can be compared. The fixture's deadline is
	// in 2030 for the same reason.
	res, err := Replay(f, time.UnixMilli(1000), &got)
	if err != nil {
		t.Fatalf("replaying the committed fixture: %v", err)
	}
	if want := len(fixtureSets) + 1; res.Records != want {
		t.Fatalf("replayed %d records, want %d", res.Records, want)
	}

	if len(got.sets) != len(fixtureSets) {
		t.Fatalf("applied %d sets, want %d: %+v", len(got.sets), len(fixtureSets), got.sets)
	}
	for i, want := range fixtureSets {
		if got.sets[i] != want {
			t.Errorf("record %d applied %+v, want %+v", i, got.sets[i], want)
		}
	}

	if len(got.deletes) != len(fixtureDeletes) {
		t.Fatalf("applied %d deletes, want %d: %v", len(got.deletes), len(fixtureDeletes), got.deletes)
	}
	for i, want := range fixtureDeletes {
		if got.deletes[i] != want {
			t.Errorf("delete %d applied %q, want %q", i, got.deletes[i], want)
		}
	}
}

// The header is asserted separately and by its bytes, because a version bump is
// exactly the moment somebody has to decide whether existing files are still
// readable. Failing here is the prompt for that decision.
func TestFixtureHeaderIsFormatVersionOne(t *testing.T) {
	data, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("reading the committed fixture: %v", err)
	}
	if len(data) < HeaderSize {
		t.Fatalf("the fixture is %d bytes, shorter than a header", len(data))
	}

	if magic := data[:8]; !bytes.Equal(magic, []byte("GOKVAOF\x00")) {
		t.Errorf("magic = %q, want %q", magic, "GOKVAOF\\x00")
	}
	if v := binary.BigEndian.Uint32(data[8:12]); v != FormatVersion {
		t.Errorf("the committed fixture is format version %d and this build writes %d; "+
			"a 1.x must read a file written by any other 1.x, so bumping the version is a "+
			"decision about existing files, not a detail", v, FormatVersion)
	}
	if FormatVersion != 1 {
		t.Errorf("FormatVersion = %d; v1.0 promises format version 1", FormatVersion)
	}
}
